# Generated by Django 4.1.2 on 2022-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_familiar_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('password_dos', models.CharField(max_length=100)),
            ],
        ),
    ]
